# cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/service-account-file.json'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET